name: Daily posts
on:
  workflow_dispatch: # Allow manual action triggering
  schedule:
    - cron: "15 23 * * *" # Run daily at 23:15 as new videos are posted at 23:00 UTC 
  
jobs:
  post_videos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create env file
        run: |
          touch .env
          echo LEMMY_USERNAME=${{ secrets.LEMMY_USERNAME }} >> .env
          echo LEMMY_PASSWORD=${{ secrets.LEMMY_PASSWORD }} >> .env
      - name: Write dropout cookies to file
        run: |
          printf "%s" "${{ secrets.DROPOUT_COOKIES }}" > dropout_cookies.txt
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Update posts!
        run: |
          python ./new_video_metadata.py
          python ./lemmy_poster.py
